# Generated by Django 2.2.6 on 2019-11-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('FT', 'Freetime'), ('MP', 'MarketPlace')], default='FT', max_length=2),
        ),
        migrations.AddField(
            model_name='tought',
            name='tought_type',
            field=models.CharField(choices=[('FT', 'Freetime'), ('MP', 'MarketPlace')], default='FT', max_length=2),
        ),
    ]
