# Generated by Django 2.2.7 on 2019-11-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191108_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_seen_survey',
            field=models.DateField(null=True),
        ),
    ]
