# Generated by Django 2.2.6 on 2019-11-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191114_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('DE', 'German'), ('IT', 'Italian'), ('EN', 'English')], default='DE', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='seen_courses',
            field=models.ManyToManyField(null=True, to='core.Course'),
        ),
    ]
