# Generated by Django 2.2.7 on 2019-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agency_is_able_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='is_able_to_do',
        ),
        migrations.AddField(
            model_name='agency',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
