# Generated by Django 2.2.6 on 2019-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191122_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='seen_courses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seen_courses',
            field=models.ManyToManyField(null=True, to='core.Course'),
        ),
    ]
