# Generated by Django 2.2.6 on 2019-11-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_to_see',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_course_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seen_courses',
            field=models.ManyToManyField(null=True, related_name='seen_by', to='core.Course'),
        ),
    ]
