# Generated by Django 2.2.6 on 2019-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191122_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_seen_survey',
            field=models.DateTimeField(null=True),
        ),
    ]
