# Generated by Django 2.2.6 on 2019-11-23 13:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191122_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.activity_directory_path),
        ),
    ]
