# Generated by Django 2.2.6 on 2019-11-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191123_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='title',
        ),
    ]
