# Generated by Django 2.2.6 on 2019-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_coursesection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
