# Generated by Django 2.2.6 on 2019-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coursesection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='encouragingsentence',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
