# Generated by Django 2.2.6 on 2019-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_curus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='curus',
            options={'verbose_name': 'Curus for the Environment Page', 'verbose_name_plural': 'Curus for the Environment Page'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Agency'),
            preserve_default=False,
        ),
    ]
