# Generated by Django 2.2.6 on 2019-12-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mood_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='color_code',
            field=models.CharField(max_length=9),
        ),
    ]
