# Generated by Django 2.2.6 on 2020-02-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191210_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encouragingsentence',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tought',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Mood'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Agency'),
        ),
    ]
