# Generated by Django 2.2.6 on 2020-02-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200208_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course_to_see',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Course'),
        ),
    ]
