# Generated by Django 2.2.6 on 2020-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200208_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ManyToManyField(blank=True, to='core.Manager'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seen_courses',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='core.Course'),
        ),
    ]
