# Generated by Django 2.2.6 on 2020-02-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200208_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='read_encouraging_sentences',
        ),
        migrations.AlterField(
            model_name='tought',
            name='motivational_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EncouragingSentence'),
        ),
    ]
