# Generated by Django 2.2.6 on 2020-02-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200208_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read_encouraging_sentences',
            field=models.ManyToManyField(blank=True, to='core.EncouragingSentence'),
        ),
    ]
