# Generated by Django 2.2.6 on 2020-02-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200208_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seen_courses',
        ),
    ]
