# Generated by Django 2.2.6 on 2020-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_userprofile_seen_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course_to_see',
        ),
    ]
