# Generated by Django 2.2.6 on 2020-02-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_userprofile_course_to_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_to_see',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seen_courses',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='core.Course'),
        ),
    ]
