# Generated by Django 2.2.6 on 2020-02-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200208_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seen_courses',
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.Course'),
        ),
    ]
