# Generated by Django 2.2.6 on 2020-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200208_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seen_courses',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='core.Course'),
        ),
    ]
