BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBB


BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX gettext(u'NEW_COURSES') XXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'NEW') XXXXXXXXXXXXXXXXXXXXXX 
                    XXXFFFFFFFFFFFFFFFFFBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBBXXXBBBBBXXXX 
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBB BBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX gettext(u'PREVIOUS_COURSES') XXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXFFFFFFFFFFFFFFFFFBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBBXXXBBBBBXXXX 
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBB BBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXFFFFFFFFFFFFFFFFFBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBBXXXBBBBBXXXX 
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBB BBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
    BB BBBBBBBBBBBBBB B B
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBB
XXXXXX
BBBBBBBB