BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXX

BBBBBBBB BBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXX XXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX XXX
        XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX
XXXXXX

    XXXX XXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBB
                    XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            FFFF
                        XXXXXX
                    XXXXXXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXXXXXX
        XX XXXX XXXX XXXXX XXXXXX X XXXXXXXXXXXXX
        XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX
            XXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXXX


        XXX
    XXXXXXXXX
XXXXXXX
    
