BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBB


BBBBB BBBBBBBBBBBBBBBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        FFFF
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            XXXXXX
        XXXXXX
        XXXXX
            XXXX XXXXXXXXXXXXXXXXFFFFFFFFXXXXXX
        XXXXXX
    XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'HAPPY_CURUS_INFO') XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'YOUR_HAPPY_TEAM') XXXX
        XXXXXX
    XXXXXX


BBBBBBBB