BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'COUNTER_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'COUNTER_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'CAUSE_EFFECT_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBB BB BBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                BBBBB BBBBBBBBBBBBB
                                XXXXXX
                            XXXXXX
                            BBBBBB
                        XXXXXX
                    XXXXXX
                XXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'CAUSE_EFFECT_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBB BB BBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            BBBBB BBBBBBBBBBBBB
                        XXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
                XXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

XXXXXX




XXXXXXXX
    
    XXX XXXXX X X
        BBB BBBB BB BBBBB
         X X
            XXXXXX  X XBBBBBB BBBBBBBBBBBBBBXX
            XXXXXXX X XX
        XX
        BBBBBB
    X
    
    XXX XXXXXXXXXXXX X X
    BBB BBBBBB BB BBBBBBB
    X
        XXXXXXX XFFFFFFFFFFFFXX XXXXX
        XXXXXXX XXX
        XXXXXXX XXX
        XXXXXXXXXXXX X XXX
        XXXXXXXXXXXXX FFFFX

        XX
        BBBBBB
    X
    XXX XXXXXXXXXXXXX X X
        BBB BBBBBB BB BBBBBBBBBBBBBBBBB
        X
            XXXXXXX XFFFFFFFFFFFFXX XXXXX
            XXXXXXX XXX
            XXXXXXX XXX
            XXXXXXXXXXXX X XXX
            XXXXXXXXXXXXX FFFFX

        XX
        BBBBBB
    X
    
    
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX X XXXXXX 
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX X XXXXXX 
    XX
    
    
    
    
    
XXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXBBB BBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
 
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX XXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
XXXXXXXXX

BBBBBBBB