BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXBBB BBBX XXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XX
            XXXX gettext(u'HISTORICAL_TREND_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BB XXXXXXXXXX BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BB XXXXXXXXXX BBBB XXX BBBBBX
                X
                X
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BB XXXXXXXXXX BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BB XXXXXXXXXX BBBB XXX BBBBBX
                X
                X
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'HISTORICAL_TREND_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    BBB BBBBB BB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'CAUSE_EFFECT_FREETIME') XXXXX
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX gettext(u'CAUSE_EFFECT_WORKPLACE') XXXXX
            XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    BBBBBB


XXXXXX



XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXBBB BBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
    XXX XXXXX X X
            BBB BBBB BB BBBBB
             X X
                XXXXXX  X XBBBBBB BBBBBBBBBBBBBBX
            XX
            BBBBBB
        X
        
    XXX XXXXX X XX    
    XXX XXXXXXXXXXXXXXXXXXXXX XX
    XXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXX XXXXXXXXXXXXX X XX
    XXX XXXXXXXXXXXX X XX
    BBB BBBBBBB BB BBBBBBBBBBBBB
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXX XX
            X 
            XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB

        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXX XX
                X 
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
        XXXXXXXXXXXXFFFFFFFFFFFFXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXX XFFFFFFFFFFFFXX XXXXX
             XXXXXXX XFFFFFFFFFFFFFFFFX
            
            XX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXX XFFFFFFFFFFFFXX XXXXX
             XXXXXXX XFFFFFFFFFFFFFFFFX 
            XX

    BBBBBB

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX X XXXXXX 
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX X XXXXXX 
    XX
    XXX XXXXX X X
        BBB BBBB BB BBBBB
         X X
            XXXXXX  X XBBBBBB BBBBBBBBBBBBBBXX
            XXXXXXX X XX

        XX
        BBBBBB
    X
    
    XXX XXXXXXXXXXXXXXXXX X X
    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        X
        XXXXXXX XXX
        XXXXXXX XXX
        XXXXXXXXXXXXX FFFFX
        XX
        BBBBBB
    X
    XXX XXXXXXXXXXXXXXXXXX X X
        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        X
            XXXXXXX XXX
            XXXXXXX XXX
            XXXXXXXXXXXXX FFFFX

        XX



        BBBBBB
    X

    
    
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX X XXXXX
        XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XBBBBBB BBBBBBBBBBBXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
        XXXXXXXXXXXXXXX
        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XBBBBBB BBBBBBBBBBBXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XX XX XX  XXXXXXX XX XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                XXXXX
                    XXXXXXXXXXXXXXX
                X
            XX
        XXXXXX
    XX
XXXXXXXXX

BBBBBBBB