BBBB BBBBBB
BBBB BBBB
XXXXXX
XXXXXX
    XXXXXXXBBBBB BBBBB XXXXXXXXXXX BBBBBBBB BBBBB X XXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
    BBBBBBBB BBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
    BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBB BBBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBB
    BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    BBBBBBBB BBBBBBBBBBBB
    BBBBB BBBBBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBXXXBBB BBBX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    
    BBBBB BBBBBBBBBBBBB
    
    BBBBBBBB BBBBBBBBBBBBB
    
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB
    BBBBBBBB BBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXX  X XXXXX
        XXXXXXXXXXXXXX  X XXXXX
        XXXXXXXXXXXXXXX X XXXXX
    
    XXXXXXXXXXXXX XX XXXXX XXXXX XXXX XXXX XXX
    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBBBBBBBBBB
XXXXXXX


XXXXXXXX
    XXXXX XXXX X X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'SELECT_A_DAY_BEFORE_TODAY') XX
        XXXXXXXXXXXXXXXX X X gettext(u'MISSING_FIELDS') XX
        XXXXXXXXXXXXXXXXXXXXXX X gettext(u'CAUSE_EFFECT_FREETIME') XX
        XXXXXXXXXXXXXXXXXXXXXXX X gettext(u'CAUSE_EFFECT_WORKPLACE') XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'COULD_NOT_PROCESS_SELECTED_DATE') XX
    X


    XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
    XX
    
XXXXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX

            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
                XXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX BB BBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXX BBBB XXXX BBBBBXXX
                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'MY_HAPPYCURUS') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'MY_STATISTICS') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'MY_LEARNING_MATERIAL') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'CURUS_FOR_THE_ENVIRONMENT') XXXX
                        XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX


XXXXXXX